--RUN This file to mssql

USE [master]
GO
/****** Object:  Database [BSCS4A_DB]    Script Date: 27/10/2022 11:24:42 am ******/
CREATE DATABASE [BSCS4A_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BSCS4A_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BSCS4A_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BSCS4A_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BSCS4A_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BSCS4A_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BSCS4A_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BSCS4A_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BSCS4A_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BSCS4A_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BSCS4A_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BSCS4A_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BSCS4A_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BSCS4A_DB] SET  MULTI_USER 
GO
ALTER DATABASE [BSCS4A_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BSCS4A_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BSCS4A_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BSCS4A_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BSCS4A_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BSCS4A_DB] SET QUERY_STORE = OFF
GO
USE [BSCS4A_DB]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 27/10/2022 11:24:42 am ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[UserID] [int] NOT NULL,
	[UserName] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[USERS] ([UserID], [UserName], [Password]) VALUES (1, N'admin', N'admin123')
INSERT [dbo].[USERS] ([UserID], [UserName], [Password]) VALUES (2, N'PogiAko_123', N'123')
INSERT [dbo].[USERS] ([UserID], [UserName], [Password]) VALUES (3, N'blackBeard', N'teach')
INSERT [dbo].[USERS] ([UserID], [UserName], [Password]) VALUES (1234, N'charles_paeste', N'pogiako')
GO
USE [master]
GO
ALTER DATABASE [BSCS4A_DB] SET  READ_WRITE 
GO
